export const visitorReviews = [
    { text: 'I had a wonderful time in the ideal apartment for couples, equipped with everything we needed, including stunning balcony and living room views. All amenities were available, the nearby host ensured smooth check-in, making it a highly recommended and satisfying experience.', author: 'Couple' },
    { text: 'The conveniently located apartment near the lake offered great swimming and amenities. It was clean, new, and surrounded by nearby conveniences like bars, restaurants, markets, and a pharmacy. Recommended for a pleasant stay.', author: 'Family with a little kid' },
    { text: 'I had a great stay at "Prima Apartments" in Pogradec for 6 nights with my family, including a toddler. The apartment was well-equipped, clean, and conveniently located, just a short walk from both the lake and city center. Owner and his family were friendly and attentive hosts, making us feel at home. Highly recommended for a wonderful holiday experience in Pogradec.', author: 'Family with a little kid' },
    { text: 'Prima Apartments a comfortable and clean accommodation with all necessary conditions!', author: 'Couple'},
    { text: "This modern vacation apartment offers quality furnishings, a balcony, and convenient amenities like an elevator. The well-equipped kitchen adds to the pleasant experience, while the building's strategic location near the beach, roads, and services including a supermarket enhances its appeal. The communicative contractors contribute to a great holiday stay.", author: 'Couple'},
    { text: 'The ideal place to rest in Pogradec, apart from comfort and cleanliness like nowhere else, an ideal location and a fantastic view!', author: 'Solo traveler'},
    { text: 'Even though I only stayed here for 2 nights, it was a pleasant experience. The property is located very near to the Ohrid Lake promenade. Close by you can find bars, restaurants, and coffee shops. Contactless checkin and checkout worked very well for me. Maximum discretion. Excellent.', author: 'Solo traveler' },
    { text: 'Easy check-in and check-out, the host is very friendly and always in touch. Large room with a nice window. Beautiful view of the city road from the balcony. Lots of dishes in the kitchen. Just a couple of minutes walk to the lake.', author: 'Couple' },
    { text: 'Excellent location, within walking distance of the center and the beach. Cozy apartment, really comfortable bed, perfect facilities and really nice landlord. A place where you feel at home. Anytime.', author: 'Couple' }
];
